---
title: "Lab2 - Checkpoint 3"
output: 
  html_document:
    theme: cosmo
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```

```{r}
respostas = read_csv(here::here("data/respostas-merepresenta-2016.csv"), 
                     col_types = cols(.default = col_character(), 
                                      nota_partido = col_integer(), 
                                      votos_recebidos = col_integer()))

# A versão long (em vez de wide) dos dados facilita muito pro ggplot:
respostas_long = 
    respostas %>% 
    gather(key = "tema", 
           value = "resposta", 
           10:23)
```

Os temas das perguntas no questionário:

```{r}
names(respostas)[10:23] 
```

Quais os temas mais e menos apoiados? 

```{r}
por_tema = 
    respostas_long %>% 
    group_by(tema) %>% 
    summarise(apoio = sum(resposta == "S") / n())

por_tema %>% 
    ggplot(aes(x = reorder(tema, apoio), y = apoio, ymax = apoio, ymin = 0)) + 
    geom_point(size = 2) + 
    geom_linerange(size = .3) + 
    scale_y_continuous(limits = c(0, 1)) + 
    coord_flip() + 
    labs(
        y = "Proporção de apoios", 
        x = ""
    )
```

Em geral, candidatos que não apoiam estado laico também não apoiam as causas LGBT e a descriminalização do aborto?
```{r}
contra_estado_laico = 
    respostas %>% 
    filter(`Estado Laico` %in% c("N")) %>% 
    gather(key = "tema", 
           value = "resposta", 
           10:23) %>%
    group_by(tema)  %>% 
    filter(tema %in% c("Descriminalização do aborto","Adoção por famílias LGBTs","Criminalização da LGBTfobia","Respeito à identidade de gênero de pessoas trans")) %>%
    summarise(apoio = sum(resposta == "S") / n())


contra_estado_laico %>% 
    ggplot(aes(x = reorder(tema, apoio), y = apoio, ymax = apoio, ymin = 0)) + 
    geom_point(size = 2) + 
    geom_linerange(size = .3) + 
    scale_y_continuous(limits = c(0, 1)) + 
    coord_flip() + 
    labs(
        y = "Proporção de apoios", 
        x = ""
    )

```
